#! /bin/bash
set -eux

DEB_MAJOR="${DEB_MAJOR:-1.13.6}"
DEB_MINOR="${DEB_MINOR:-2}"
DEB_VERSION="$DEB_MAJOR.$DEB_MINOR"
DEB_PACKAGE="trafficplex8"
OPENSSL_VERSION="1.1.1g"

echo "Building $DEB_VERSION-$DEB_PACKAGE.de"
sudo docker pull ubuntu:trusty

sudo docker build --build-arg DEB_MAJOR=$DEB_MAJOR \
                  --build-arg DEB_MINOR=$DEB_MINOR \
                  --build-arg DEB_VERSION=$DEB_VERSION \
                  --build-arg DEB_PACKAGE=$DEB_PACKAGE \
                  --build-arg OPENSSL_VERSION=$OPENSSL_VERSION \
                  -t openresty-bundle-deb .
CONTAINER=$(sudo docker create openresty-bundle-deb)
if [ ! -d ./artifacts ]; then
    mkdir ./artifacts
fi
sudo docker cp $CONTAINER:/build/openresty_$DEB_VERSION-${DEB_PACKAGE}_amd64.deb ./artifacts/
sudo docker rm $CONTAINER
